export const siteConfig = {
  name: "Zach Varney",
  title: "Zach Varney - AI Technical Product Manager",
  description: "AI Technical Product Manager specializing in LLM-powered applications, agentic workflows, and scalable AI solutions. Expert in product discovery, evaluation frameworks, and shipping AI products that actually work.",
  url: "https://zvarney.com",
  ogImage: "https://zvarney.com/og.jpg",
  links: {
    twitter: "https://twitter.com/zvarney",
    github: "https://github.com/zvarney",
    linkedin: "https://www.linkedin.com/in/zach-varney/",
  },
  author: {
    name: "Zach Varney",
    email: "z.varney.business@gmail.com",
    jobTitle: "AI Technical Product Manager",
    company: "Independent Consultant",
    location: "Kansas City, MO",
    bio: "AI Technical PM with 1.5 years building LLM-powered products. Expert in agentic workflows, evaluation frameworks, and shipping AI products that actually work.",
  },
  navigation: [
    { title: "Home", href: "/" },
    { title: "About", href: "/about" },
    { title: "Timeline", href: "/timeline" },
    { title: "Case Studies", href: "/case-studies" },
    { title: "Blog", href: "/blog" },
    // { title: "Tools", href: "/tools" },
    { title: "FAQ", href: "/faq" },
    { title: "Resume", href: "/resume" },
  ],
  expertise: [
    "AI Product Management",
    "LLM Applications",
    "Agentic Workflows", 
    "Product Discovery",
    "Evaluation Frameworks",
    "Technical Strategy",
    "Team Leadership",
    "Go-to-Market",
  ],
  technologies: [
    "Python",
    "TypeScript",
    "React",
    "Next.js",
    "OpenAI API",
    "Anthropic Claude",
    "LangChain",
    "Vector Databases",
    "AWS",
    "Docker",
  ],
} 