export const siteConfig = {
  name: "Zach Varney",
  title: "Zach Varney — AI-First Product Strategist Who Ships Code",
  description: "AI-first product strategist with a developer background. I don't just build roadmaps — I build products. 12K+ lines shipped, 2 working interactive tools, 3 production AI case studies. Currently at Lytho driving AI-first product strategy.",
  url: "https://zvarney.com",
  ogImage: "https://zvarney.com/og.jpg",
  links: {
    twitter: "https://twitter.com/zvarney",
    github: "https://github.com/zvarney",
    linkedin: "https://www.linkedin.com/in/zach-varney/",
  },
  author: {
    name: "Zach Varney",
    email: "z.varney.business@gmail.com",
    jobTitle: "AI-First Product Strategist",
    company: "Lytho",
    location: "Kansas City, MO",
    bio: "AI-first product strategist with a developer background. I ship code, not just strategy docs. 12+ years B2B SaaS, currently driving AI product strategy at Lytho.",
  },
  navigation: [
    { title: "Home", href: "/" },
    { title: "About", href: "/about" },
    { title: "Timeline", href: "/timeline" },
    { title: "Tools", href: "/tools" },
    { title: "FAQ", href: "/faq" },
    { title: "Resume", href: "/resume" },
  ],
  expertise: [
    "AI Product Management",
    "LLM Applications",
    "Agentic Workflows", 
    "Product Discovery",
    "Evaluation Frameworks",
    "Technical Strategy",
    "Team Leadership",
    "Go-to-Market",
  ],
  technologies: [
    "Python",
    "TypeScript",
    "React",
    "Next.js",
    "OpenAI API",
    "Anthropic Claude",
    "LangChain",
    "Vector Databases",
    "AWS",
    "Docker",
  ],
} 